# Generated by Django 6.0.5 on 2026-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_id_card_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='id_card_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_id_proofs/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='id_verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='staff_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
