# Generated by Django 6.0.5 on 2026-05-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='id_card_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programme',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
