# Generated by Django 6.0.5 on 2026-05-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_studentprofile_id_review_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='id_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
