# Generated by Django 6.0.5 on 2026-05-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strike_count', models.PositiveIntegerField(default=0)),
                ('max_strikes', models.PositiveIntegerField(default=3)),
                ('id_verification_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('id_verification_attempts', models.PositiveIntegerField(default=0)),
                ('lockdown_active', models.BooleanField(default=False)),
                ('last_frame_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='exams.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='IDVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_image', models.ImageField(blank=True, upload_to='id_verification/')),
                ('detected_id_type', models.CharField(blank=True, max_length=100)),
                ('id_confidence_score', models.FloatField(default=0)),
                ('face_match_score', models.FloatField(default=0)),
                ('id_check_passed', models.BooleanField(default=False)),
                ('face_check_passed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_attempts', to='proctoring.proctoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('phone', 'Mobile Phone'), ('book', 'Book'), ('notes', 'Notes'), ('absent', 'Student Absent'), ('multiple_faces', 'Multiple People'), ('face_obstructed', 'Face Obstructed'), ('tab_switch', 'Tab Switch'), ('focus_lost', 'Focus Lost'), ('exit_fullscreen', 'Exit Fullscreen')], max_length=30)),
                ('confidence', models.FloatField(default=0)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('strike_number', models.PositiveIntegerField(default=1)),
                ('action_taken', models.CharField(choices=[('warning', 'Warning'), ('terminate', 'Terminate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='proctoring.proctoringsession')),
            ],
        ),
        migrations.CreateModel(
            name='ViolationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='violations/')),
                ('bounding_boxes', models.JSONField(blank=True, default=list)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='proctoring.violationlog')),
            ],
        ),
        migrations.AddIndex(
            model_name='violationlog',
            index=models.Index(fields=['session', 'created_at'], name='proctoring__session_49a431_idx'),
        ),
    ]
