# Generated by Django 6.0.5 on 2026-05-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationlog',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
