# Generated by Django 6.0.5 on 2026-06-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0003_violationlog_review_status_violationlog_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='absent_frame_streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive ML frames with no person detected (for absent rule).'),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='frame_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='frame_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='violationsnapshot',
            name='pose_keypoints',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
