# Generated by Django 6.0.5 on 2026-07-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_max_strikes_default_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='multi_person_frame_streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive ML frames with 2+ persons detected (multiple-person rule only strikes after MULTIPLE_PERSON_CONSECUTIVE_FRAMES).'),
        ),
    ]
