"""Dataset capture + YOLO-format labeling for fine-tuning.

The lab trains a small custom detector for the infraction-relevant objects. Class
indices below are **local to the dataset** (YOLO expects 0-based contiguous ids),
and we map the COCO ids the base model emits onto them for auto-label assist.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np

from ml.yolo_service.detector import Detection

# Local (dataset) class order. Index = the id written into YOLO label files.
# remote/mouse are included as their own classes so fine-tuning can learn to
# tell a phone apart from these common phone-confusable desk objects (hard
# negatives) instead of false-flagging them.
LAB_CLASSES = ["person", "phone", "book", "laptop", "keyboard", "remote", "mouse"]

# COCO class id (what the base model emits) -> local dataset index.
COCO_TO_LAB = {0: 0, 67: 1, 73: 2, 63: 3, 66: 4, 65: 5, 64: 6}

_DATASET_ROOT = Path(__file__).resolve().parent / "dataset"


@dataclass
class LabelCandidate:
    """A proposed YOLO label, pre-filled from a model detection."""

    lab_index: int
    label: str
    cx: float
    cy: float
    w: float
    h: float
    confidence: float


def dataset_root() -> Path:
    return _DATASET_ROOT


def dataset_dirs(create: bool = True) -> tuple[Path, Path]:
    """Return (images_dir, labels_dir), creating them if requested."""
    images = _DATASET_ROOT / "images"
    labels = _DATASET_ROOT / "labels"
    if create:
        images.mkdir(parents=True, exist_ok=True)
        labels.mkdir(parents=True, exist_ok=True)
    return images, labels


def detections_to_label_candidates(detections: list[Detection]) -> list[LabelCandidate]:
    """Convert model detections into editable YOLO label candidates.

    Detection boxes are top-left normalized (x, y, w, h); YOLO labels are
    center-normalized (cx, cy, w, h).
    """
    candidates: list[LabelCandidate] = []
    for det in detections:
        lab_index = COCO_TO_LAB.get(det.class_id)
        if lab_index is None:
            continue
        cx = det.x + det.w / 2
        cy = det.y + det.h / 2
        candidates.append(
            LabelCandidate(
                lab_index=lab_index,
                label=LAB_CLASSES[lab_index],
                cx=round(cx, 6),
                cy=round(cy, 6),
                w=round(det.w, 6),
                h=round(det.h, 6),
                confidence=det.confidence,
            )
        )
    return candidates


def _timestamp_stem() -> str:
    return _dt.datetime.now().strftime("frame_%Y%m%d_%H%M%S_%f")


def save_sample(image_bgr: np.ndarray, labels: list[LabelCandidate]) -> Path:
    """Write one image + its YOLO label file. Empty ``labels`` writes a valid
    empty label file (a legitimate background/negative sample)."""
    images_dir, labels_dir = dataset_dirs(create=True)
    stem = _timestamp_stem()
    image_path = images_dir / f"{stem}.jpg"
    label_path = labels_dir / f"{stem}.txt"

    cv2.imwrite(str(image_path), image_bgr)

    lines = [
        f"{lc.lab_index} {lc.cx:.6f} {lc.cy:.6f} {lc.w:.6f} {lc.h:.6f}"
        for lc in labels
    ]
    label_path.write_text("\n".join(lines) + ("\n" if lines else ""))
    return image_path


def count_samples() -> int:
    images_dir, _ = dataset_dirs(create=False)
    if not images_dir.exists():
        return 0
    return len(list(images_dir.glob("*.jpg")))


def write_data_yaml() -> Path:
    """Write Ultralytics data.yaml. For a small lab set we point train and val
    at the same image folder; split more carefully for larger datasets."""
    images_dir, _ = dataset_dirs(create=True)
    yaml_path = _DATASET_ROOT / "data.yaml"
    names = "\n".join(f"  {i}: {name}" for i, name in enumerate(LAB_CLASSES))
    yaml_path.write_text(
        "# Auto-generated by ml/lab/capture.py\n"
        f"path: {_DATASET_ROOT.as_posix()}\n"
        "train: images\n"
        "val: images\n"
        f"nc: {len(LAB_CLASSES)}\n"
        "names:\n"
        f"{names}\n"
    )
    return yaml_path
