# Generated by Django 6.0.5 on 2026-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examattempt_pause_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='strictness_level',
            field=models.CharField(choices=[('none', 'Not strict — no proctoring checks'), ('level_1', 'Level 1 — 3-strike tolerance'), ('level_2', 'Level 2 — no second chances')], default='level_1', help_text="Lockdown policy for this exam. Level 1 (default) follows the 3-strike rule; Level 2 is zero-tolerance; 'Not strict' disables all checks.", max_length=16),
        ),
    ]
