# Generated by Django 6.0.5 on 2026-05-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_violationlog_disputed_at_violationlog_is_disputed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violationlog',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('confirmed', 'Confirmed Violation'), ('ignored', 'Ignored'), ('false_alarm', 'Resolved — False Alarm'), ('escalated', 'Escalated')], default='pending_review', max_length=20),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='severity_overridden',
            field=models.BooleanField(default=False, help_text='True when a teacher manually changed the AI-assigned severity.'),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='teacher_note',
            field=models.TextField(blank=True, help_text='Optional teacher message shown to the student on their result page.'),
        ),
        migrations.AlterField(
            model_name='violationlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='violationlog',
            index=models.Index(fields=['review_status'], name='proctoring__review__bfd054_idx'),
        ),
    ]
