# Generated by Django 6.0.5 on 2026-06-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0004_yolo_snapshot_pose_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringsession',
            name='look_away_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsession',
            name='look_away_struck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ViolationClipFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='violation_clips/')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_frames', to='proctoring.violationlog')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['violation', 'sequence'], name='proctoring__violati_252c63_idx')],
            },
        ),
    ]
