# Generated by Django 6.0.5 on 2026-07-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0007_proctoringsession_multi_person_frame_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationsnapshot',
            name='gaze_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
