# Generated by Django 6.0.5 on 2026-05-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_approve_published_exams'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='pause_reason',
            field=models.CharField(blank=True, choices=[('freeze', 'Frozen by administrator'), ('disconnect', 'Student disconnected')], default='', max_length=20),
        ),
    ]
