# Generated by Django 6.0.5 on 2026-05-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_strictness_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invalidated_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='invalidation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_invalidated',
            field=models.BooleanField(default=False),
        ),
    ]
